### ISSUE TITLE
Checklist Assignment 1

### ISSUE THREAD

**Issue by mattijsgietman** [NiekGrimbergen/WebTech#1]
- [x] have at least 5 pages with meaningful content
- [x] use HTML5 semantic attributes for formatting the layout of your pages
- [x] use images
- [x] have links between pages, within pages, and to external page(s)
- [x] have at least one table (not used for formatting a webpage layout)
- [ ] be optimized for search engines
- [x] use consistent layout and color scheme
- [ ] use CSS for formatting, including at least:

   - [ ] several different styles for links
   - [ ] several different styles for text
   - [x] styles for table elements
   - [ ] cascading styles through selector specificity
   - [ ] style inheritance

- [x] define all formatting styles in a separate CSS file
- [ ] be compliant with the HTML5 rules of W3C Markup Validation Service and the CSS3 rules of W3C CSS Validation Service
- [ ] not use any of the deprecated HTML elements or attributes
- [ ] render correctly in the current versions of Chrome and Firefox browsers
- [ ] follow the Web accessibility standard on

    - [ ] Keyboard compatibility
    - [ ] Text to speech
    - [ ] Clear layout and design
    - [ ] Customizable text
    - [ ] Understandable content

- [ ] follow the responsive Web design guidelines for

   - [ ]  Images
   - [ ]  content positioning
   - [ ]  units of measuremen

**Comment by NiekGrimbergen** [comment]
https://www.w3.org/WAI/WCAG21/quickref/ voor Web Accessibility Standard

**Comment by NiekGrimbergen** [comment]
https://www.svgrepo.com/collection/round-bordered-company-logo-icons/2

**Comment by NiekGrimbergen** [comment]
https://www.w3.org/WAI/quicktips/
